<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="validate_colors_list_tests.TestValidateColorsList-20181017205330" skipped="0" tests="3" time="0.001" timestamp="2018-10-17T20:53:30">
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" name="testValidateColorsListWhenColorsListContainsOneColor" time="0.000" timestamp="2018-10-17T20:53:30"/>
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" name="testValidateColorsListWhenColorsListIsEmpty" time="0.000" timestamp="2018-10-17T20:53:30"/>
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" name="testValidateColorsListWhenColorsListIsNone" time="0.001" timestamp="2018-10-17T20:53:30">
		<error message="object of type 'NoneType' has no len()" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/Users/ras/Projects/Python/cs3280/project2/src/unittest/python/validate_colors_list_tests.py", line 8, in testValidateColorsListWhenColorsListIsNone
    self.assertRaises(ValueError, validateColorsList(None))
  File "/Users/ras/Projects/Python/cs3280/project2/src/main/python/resistor.py", line 22, in validateColorsList
    len(colors) > 0 and len(colors) < 4
TypeError: object of type 'NoneType' has no len()
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
