<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="validate_colors_list_tests.TestValidateColorsList-20181017202608" skipped="0" tests="2" time="0.001" timestamp="2018-10-17T20:26:08">
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" name="testValidateColorsListWhenColorsListIsNone" time="0.000" timestamp="2018-10-17T20:26:08"/>
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" name="testValidateColorsListWhenColorsListIsEmpty" time="0.001" timestamp="2018-10-17T20:26:08">
		<failure message="True is not false" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/Users/ras/Projects/Python/cs3280/project2/src/unittest/python/validate_colors_list_tests.py", line 15, in testValidateColorsListWhenColorsListIsEmpty
    self.assertFalse(result)
AssertionError: True is not false
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
